apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: edueval
type: Opaque
stringData:
  DB_USERNAME: root
  DB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_USE_A_LONG_RANDOM_STRING
  OPENAI_API_KEY: CHANGE_ME
